<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Mcp.Benchmark.CLI/Mcp.Benchmark.CLI.csproj" />
    <ProjectReference Include="../Mcp.Benchmark.Infrastructure/Mcp.Benchmark.Infrastructure.csproj" />
  </ItemGroup>
</Project>
