import sys

file_path = 'Mcp.Benchmark.Infrastructure/Services/Reporting/ValidationHtmlReportComposer.cs'
with open(file_path, 'r') as f:
    lines = f.readlines()

method_start = -1
method_end = -1
for i, line in enumerate(lines):
    if 'private static string RenderFindingStacks(ValidationHtmlReportDocument document)' in line:
        method_start = i
    if method_start != -1 and line.strip() == '}' and method_end == -1:
        if i > method_start:
             method_end = i

if method_start != -1 and method_end != -1:
    content = """    private static string RenderFindingStacks(ValidationHtmlReportDocument document)
    {
        var sb = new StringBuilder();
        sb.AppendLine("          <div class=\"stack-grid\">");
        sb.AppendLine(RenderFindingStack(
            "Priority Findings",
            "Read these first",
            document.PriorityFindings,
            HtmlReportTone.Warning));
        sb.AppendLine(RenderFindingStack(
            "Action Hints",
            "Next moves",
            document.ActionHints.Count > 0 ? document.ActionHints : document.AdditionalRecommendations,
            HtmlReportTone.Info));
        sb.AppendLine("          </div>");
        sb.AppendLine($"<div class=\"footer\">Generated by MCP Validator · {Encode(document.DetailLabel)} report · print-ready HTML for PDF export</div>");
        return sb.ToString();
    }
"""
    final_output = lines[:method_start] + [content] + lines[method_end+1:]
    with open(file_path, 'w') as f:
        f.writelines(final_output)
