/**
 * Tool handlers — maps MCP tool calls to mcpval CLI execution.
 * Each handler builds CLI args from validated input, runs the CLI, and formats output.
 * All outputs are sanitized to prevent injection payload reflection.
 */
import { runCli, isCliAvailable, getCliVersion } from "./cli-runner.js";
import type { z } from "zod";
import type { ValidateInputSchema, HealthCheckInputSchema, DiscoverInputSchema } from "./tools.js";

type ValidateInput = z.infer<typeof import("./tools.js").ValidateInputSchema>;
type HealthCheckInput = z.infer<typeof import("./tools.js").HealthCheckInputSchema>;
type DiscoverInput = z.infer<typeof import("./tools.js").DiscoverInputSchema>;

export interface ToolExecutionResult {
  text: string;
  isError: boolean;
}

/**
 * Handles the `validate` tool call.
 */
export async function handleValidate(input: ValidateInput): Promise<ToolExecutionResult> {
  const available = await isCliAvailable();
  if (!available) return { text: cliNotInstalledMessage(), isError: true };

  const args: string[] = [];
  if (input.policy) args.push("--policy", input.policy);
  if (input.mcpspec) args.push("--mcpspec", input.mcpspec);
  if (input.reportDetail) args.push("--report-detail", input.reportDetail);
  if (input.interactive) args.push("--interactive");
  if (input.verbose) args.push("-v");
  if (input.clientProfile?.length) {
    for (const profile of input.clientProfile) {
      args.push("--client-profile", profile);
    }
  }

  const result = await runCli({
    command: "validate",
    args,
    captureResultJson: true,
    configJson: buildServerConfig(input.server, input.access, input.token, input.interactive),
  });

  if (result.resultJson) {
    return {
      text: cleanOutput(formatValidationResult(result.resultJson)),
      isError: false,
    };
  }

  return {
    text: cleanOutput(result.stdout || result.stderr || "Validation completed with no output."),
    isError: result.exitCode !== 0,
  };
}

/**
 * Handles the `health_check` tool call.
 */
export async function handleHealthCheck(input: HealthCheckInput): Promise<ToolExecutionResult> {
  const available = await isCliAvailable();
  if (!available) return { text: cliNotInstalledMessage(), isError: true };

  const args: string[] = [];
  if (input.interactive) args.push("--interactive");

  const result = await runCli({
    command: "health-check",
    args,
    configJson: buildServerConfig(input.server, input.access, input.token, input.interactive),
  });

  return {
    text: cleanOutput(result.stdout || result.stderr || "Health check completed."),
    isError: result.exitCode !== 0,
  };
}

/**
 * Handles the `discover` tool call.
 */
export async function handleDiscover(input: DiscoverInput): Promise<ToolExecutionResult> {
  const available = await isCliAvailable();
  if (!available) return { text: cliNotInstalledMessage(), isError: true };

  const args = ["--format", input.format];
  if (input.interactive) args.push("--interactive");

  const result = await runCli({
    command: "discover",
    args,
    configJson: buildServerConfig(input.server, input.access, input.token, input.interactive),
  });

  return {
    text: cleanOutput(result.stdout || result.stderr || "Discovery completed."),
    isError: result.exitCode !== 0,
  };
}

// ─── Output Handling ─────────────────────────────────────────

/**
 * Processes CLI output before returning to AI agents.
 * 
 * Note on sanitization: MCP spec says "Servers MUST sanitize tool outputs" —
 * this applies to servers that echo untrusted user input (like an echo tool).
 * Our tools run the mcpval CLI and return its structured report. The report
 * is generated by our own trusted code, not echoed from user input.
 * 
 * We DO strip control characters (null bytes, etc.) that could corrupt
 * the JSON-RPC transport, but we do NOT strip report content like URLs,
 * code examples, or security findings — those are the value of the tool.
 */
function cleanOutput(text: string): string {
  // Only strip characters that could break JSON-RPC transport
  return text.replace(/[\x00-\x08\x0e-\x1f\x7f]/g, "");
}

// ─── Helpers ─────────────────────────────────────────────────

function cliNotInstalledMessage(): string {
  return [
    "mcpval CLI is not installed or not on PATH.",
    "",
    "Install:",
    "  dotnet tool install --global McpVal",
    "",
    "Update to latest:",
    "  dotnet tool update --global McpVal",
    "",
    "Or download from: https://github.com/navalerakesh/mcp-validation-security/releases",
  ].join("\n");
}

function buildServerConfig(
  server: string,
  access: "public" | "authenticated" | "enterprise" | "unspecified",
  token?: string,
  interactive = false,
): Record<string, unknown> {
  const authentication = token || interactive
    ? {
        type: token ? "bearer" : "none",
        required: access === "authenticated" || access === "enterprise",
        token,
        allowInteractive: interactive,
      }
    : undefined;

  return {
    server: {
      endpoint: server,
      transport: inferTransport(server),
      profile: mapAccessProfile(access),
      authentication,
    },
  };
}

function inferTransport(server: string): "http" | "websocket" | "stdio" {
  const trimmed = server.trim();
  if (/^https?:\/\//i.test(trimmed)) return "http";
  if (/^wss?:\/\//i.test(trimmed)) return "websocket";
  return "stdio";
}

function mapAccessProfile(access: "public" | "authenticated" | "enterprise" | "unspecified"): number {
  switch (access) {
    case "public":
      return 1;
    case "authenticated":
      return 2;
    case "enterprise":
      return 3;
    default:
      return 0;
  }
}

function formatValidationResult(json: Record<string, unknown>): string {
  const lines: string[] = [];

  const score = json.complianceScore ?? json.ComplianceScore;
  const status = json.overallStatus ?? json.OverallStatus;
  const trust = json.trustAssessment as Record<string, unknown> | undefined;
  const recommendations = json.recommendations as unknown[] | undefined;
  const summary = json.summary as Record<string, unknown> | undefined;

  lines.push(`Status: ${status}`);
  lines.push(`Compliance Score: ${score}%`);

  if (trust) {
    lines.push(`Trust Level: ${trust.trustLabel ?? trust.TrustLabel}`);
    lines.push(`  Protocol: ${trust.protocolCompliance ?? trust.ProtocolCompliance}%`);
    lines.push(`  Security: ${trust.securityPosture ?? trust.SecurityPosture}%`);
    lines.push(`  AI Safety: ${trust.aiSafety ?? trust.AiSafety}%`);
    lines.push(`  Operations: ${trust.operationalReadiness ?? trust.OperationalReadiness}%`);
  }

  if (summary) {
    lines.push(`Tests: ${summary.passedTests ?? summary.PassedTests}/${summary.totalTests ?? summary.TotalTests} passed`);
    lines.push(`Warnings: ${summary.warnings ?? summary.Warnings ?? 0}`);
  }

  if (Array.isArray(recommendations) && recommendations.length > 0) {
    lines.push("Top Recommendations:");
    for (const recommendation of recommendations.slice(0, 3)) {
      if (typeof recommendation === "string") {
        lines.push(`- ${recommendation}`);
      }
    }
  }

  return lines.join("\n");
}
