/**
 * Tool handlers — maps MCP tool calls to mcpval CLI execution.
 * Each handler builds CLI args from validated input, runs the CLI, and formats output.
 * All outputs are sanitized to prevent injection payload reflection.
 */
import { runCli, isCliAvailable, getCliVersion } from "./cli-runner.js";
import type { z } from "zod";
import type { ValidateInputSchema, HealthCheckInputSchema, DiscoverInputSchema } from "./tools.js";

type ValidateInput = z.infer<typeof import("./tools.js").ValidateInputSchema>;
type HealthCheckInput = z.infer<typeof import("./tools.js").HealthCheckInputSchema>;
type DiscoverInput = z.infer<typeof import("./tools.js").DiscoverInputSchema>;

/**
 * Handles the `validate` tool call.
 */
export async function handleValidate(input: ValidateInput): Promise<string> {
  const available = await isCliAvailable();
  if (!available) return cliNotInstalledMessage();

  const args = ["validate", "-s", input.server, "--access", input.access];
  if (input.token) args.push("-t", input.token);
  if (input.mcpspec) args.push("--mcpspec", input.mcpspec);
  if (input.verbose) args.push("-v");

  const result = await runCli(args);

  if (result.resultJson) {
    return cleanOutput(formatValidationResult(result.resultJson));
  }

  return cleanOutput(result.stdout || result.stderr || "Validation completed with no output.");
}

/**
 * Handles the `health_check` tool call.
 */
export async function handleHealthCheck(input: HealthCheckInput): Promise<string> {
  const available = await isCliAvailable();
  if (!available) return cliNotInstalledMessage();

  const args = ["health-check", "-s", input.server];
  if (input.token) args.push("-t", input.token);

  const result = await runCli(args);
  return cleanOutput(result.stdout || result.stderr || "Health check completed.");
}

/**
 * Handles the `discover` tool call.
 */
export async function handleDiscover(input: DiscoverInput): Promise<string> {
  const available = await isCliAvailable();
  if (!available) return cliNotInstalledMessage();

  const args = ["discover", "-s", input.server, "--format", "json"];
  if (input.token) args.push("-t", input.token);

  const result = await runCli(args);
  return cleanOutput(result.stdout || result.stderr || "Discovery completed.");
}

// ─── Output Handling ─────────────────────────────────────────

/**
 * Processes CLI output before returning to AI agents.
 * 
 * Note on sanitization: MCP spec says "Servers MUST sanitize tool outputs" —
 * this applies to servers that echo untrusted user input (like an echo tool).
 * Our tools run the mcpval CLI and return its structured report. The report
 * is generated by our own trusted code, not echoed from user input.
 * 
 * We DO strip control characters (null bytes, etc.) that could corrupt
 * the JSON-RPC transport, but we do NOT strip report content like URLs,
 * code examples, or security findings — those are the value of the tool.
 */
function cleanOutput(text: string): string {
  // Only strip characters that could break JSON-RPC transport
  return text.replace(/[\x00-\x08\x0e-\x1f\x7f]/g, "");
}

// ─── Helpers ─────────────────────────────────────────────────

function cliNotInstalledMessage(): string {
  return [
    "mcpval CLI is not installed or not on PATH.",
    "",
    "Install:",
    "  dotnet tool install --global Mcp.Benchmark.CLI",
    "",
    "Update to latest:",
    "  dotnet tool update --global Mcp.Benchmark.CLI",
    "",
    "Or download from: https://github.com/navalerakesh/mcp-benchmark-validation/releases",
  ].join("\n");
}

function formatValidationResult(json: Record<string, unknown>): string {
  const lines: string[] = [];

  const score = json.complianceScore ?? json.ComplianceScore;
  const status = json.overallStatus ?? json.OverallStatus;
  const trust = json.trustAssessment as Record<string, unknown> | undefined;

  lines.push(`Status: ${status}`);
  lines.push(`Compliance Score: ${score}%`);

  if (trust) {
    lines.push(`Trust Level: ${trust.trustLabel ?? trust.TrustLabel}`);
    lines.push(`  Protocol: ${trust.protocolCompliance ?? trust.ProtocolCompliance}%`);
    lines.push(`  Security: ${trust.securityPosture ?? trust.SecurityPosture}%`);
    lines.push(`  AI Safety: ${trust.aiSafety ?? trust.AiSafety}%`);
    lines.push(`  Operations: ${trust.operationalReadiness ?? trust.OperationalReadiness}%`);
  }

  return lines.join("\n");
}
